### ISSUE TITLE
The definition of buyer in the class of HouseBuyerRecord is not correct.

### ISSUE THREAD

**Issue by cz293** [adrian-carro/spatial-housing-model#24]
The incorrect code: 
public Household buyer; // Who wants to buy the house

This is not exact, as the so-called buyer could be either purchaser or renter
This class has been used in both sale and rental markets.

**Comment by adrian-carro** [comment]
In the future, names of record classes should be changed as:
HouseBuyerRecord ---> HouseBidderRecord
HouseSaleRecord ---> HouseOfferRecord

**Comment by adrian-carro** [comment]
Note that this affects also the non-spatial model!

**Comment by adrian-carro** [comment]
Also, remove BTLBuyerRecord and replace it by a boolean variable within HouseBuyerRecord and change RegionQualityRecord name to QualityBandRecord.

**Comment by adrian-carro** [comment]
Finally, RegionQualityRecord has been removed and replaced not by a record object (extending HousingMarketRecord), but rather by a simple container, RegionQualityPriceContainer.
All solved by commits 4dc9e8f929120f3ebd52d1c42769c7ab0f38c9e2 and a1a5c192b59876651ba63a475199dcfb2ab1bb7a
